### ISSUE TITLE
Convert github workflows to docker buildx bake

### ISSUE THREAD

**Issue by usrbinkat** [ContainerCraft/qubo#23]
Dependent on buildx bake adoption across image tree.
https://github.com/marketplace/actions/docker-buildx-bake

**Comment by jbpratt** [comment]
testing this out so far

successful build of amd64 ubuntu with bake https://github.com/ContainerCraft/qubo/runs/4321541591?check_suite_focus=true
unsuccessful build(s) of arm64 ubuntu with bake https://github.com/ContainerCraft/qubo/runs/4321941372?check_suite_focus=true
 
```
#8 83.05 Could not access KVM kernel module: No such file or directory
#8 83.05 qemu-system-aarch64: failed to initialize KVM: No such file or directory
#8 83.06 qemu-system-aarch64: Back to tcg accelerator
#8 83.06 qemu-system-aarch64: gic-version=host requires KVM
```

**Comment by jbpratt** [comment]
Closing this as a success! Images are now being built via bake in the `kmi` repository (https://github.com/ContainerCraft/kmi/blob/e83e34dd59213240c389e36c8959d0199dedd4aa/.github/workflows/bake.yml)
