### ISSUE TITLE
Split qubo into separate repos for image building & vm image definitions

### ISSUE THREAD

**Issue by usrbinkat** [ContainerCraft/qubo#24]
## Observation:
This repo currently represents two separate functions:
  1. building images
  2. publishing a kubevirt guest library of vm definitions

## Problem:
This repo identity split causes confusion and impedes potential to upstream & collaborate with the greater kubevirt project on standard image preparation and publishing practices.

## Proposal:
Split this repo into separate repositories dedicated to concise objectives.
  1. containercraft/qubo should remain as the library of vm definitions
  2. containercraft/containerdisks should be the container disk publishing tasks

**Comment by usrbinkat** [comment]
Initialized upstream containerdisks fork https://github.com/ContainerCraft/containerdisks/tree/ccio

Set default branch for containercraft development trunk to `ccio` & disabled committing directly to upstream trunk `main`

**Comment by jbpratt** [comment]
Removed all image build from the `main` branch of `qubo` (163023e)

**Comment by jbpratt** [comment]
closing this as the repos have been split
